module.exports =
  TODO_TOGGLE: 'TODO_TOGGLE'
  TODO_ADD: 'TODO_ADD'
  LOAD_TODOS: 'LOAD_TODOS'
  LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS'
  LOAD_TODOS_FAIL: 'LOAD_TODOS_FAIL'
  SEARCH_TODO: 'SEARCH_TODO'
  REMOVE_TODO: 'REMOVE_TODO'
